<?php

/**
 * @file
 * String overrides.
 */

$conf['locale_custom_strings_en'][''] = array(
  'State' => 'County',
  'You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.' => 'You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password, or create one if you are a new user.',
  'Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.' => 'Please choose a unique username you will use to login to the site. Spaces are allowed; punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.',
  'The changes have been saved.' => 'The changes have been saved. If you have set your password for the first time you will now be able to access your details and subscriptions through the My Account tab at the top',
);
