<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'rmets_cpd_accreditation_features.features.inc';

/**
 * Implements hook_commerce_line_item_default_types().
 */
function rmets_cpd_accreditation_features_commerce_line_item_default_types() {
  $items = array(
    'rmets_accreditation' => array(
      'name' => 'RMetS Accreditation',
      'description' => 'A customizable product line item type.',
      'product' => TRUE,
      'add_form_submit_value' => 'Add product',
      'base' => 'commerce_product_line_item',
    ),
  );
  return $items;
}
